$axure.loadCurrentPage({
  "url":"savefrom.html",
  "generationDate":new Date(1523980540664.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6ebac19daa5341b992baa436347f5b16",
    "type":"Axure:Page",
    "name":"savefrom",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0797725e50834de78e469ed0a4741176",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":1170,
              "height":1450},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949bf6929764447688e040785fc0c4be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":1170,
                  "height":1450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u0.png"}},
{
          "id":"d8f2ee293f7d4e109dfbaaac2a4e252b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":4},
            "size":{
              "width":1160,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be8930ddacef4e24b0148a05e20e3e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":4},
                "size":{
                  "width":1160,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u2.png"}},
{
          "id":"357128ce7fea41178ae537d4a825fae3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":15},
            "size":{
              "width":280,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd6847c4b910412a9e90749631766e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":15},
                "size":{
                  "width":280,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u4.png"}},
{
          "id":"28028f3cd21b4fa8a08e434295d332a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":530,
              "y":26},
            "size":{
              "width":138,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20fa0aa0c0047898bbf848e61223359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":530,
                  "y":26},
                "size":{
                  "width":138,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b9e3108c1d04eeabdd851b8a7762411",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":706,
              "y":26},
            "size":{
              "width":164,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aac44495b5164648ab7d148e4e9d37a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":706,
                  "y":26},
                "size":{
                  "width":164,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9b5513d5f874f80a9f0f584aa1fa1e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":1167,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8209f15467842debba6db306960fd41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":1167,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u10.png"}},
{
          "id":"cfb31efd09144f798aaa7cc7bee362cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":90},
            "size":{
              "width":390,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f179876f9a4053ba4eee9603366757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":90},
                "size":{
                  "width":390,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u12.png"}},
{
          "id":"4173c237d044429b9b24a06d87fa11f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":108},
            "size":{
              "width":426,
              "height":202}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169557af81414c0c871c0bdef9295d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":108},
                "size":{
                  "width":426,
                  "height":202}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u14.png"}},
{
          "id":"4c364484a98e4ca9ba0f014eb6dcd696",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":178},
            "size":{
              "width":526,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f0afaeac40940f58235aeb58cc71cb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":178},
                "size":{
                  "width":526,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u16.png"}},
{
          "id":"8f5180b1a27b48c7ae039d84f73b7413",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":185},
            "size":{
              "width":83,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42010712318b461ea2c5bce02dd2bfed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":185},
                "size":{
                  "width":83,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u18.png"}},
{
          "id":"78f84b997acf4d47bb764e84326cd210",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":180},
            "size":{
              "width":140,
              "height":67}},
          "adaptiveStyles":{
}},
{
          "id":"fa53287881534bdf8d6cdf5fb4457bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":130},
            "size":{
              "width":670,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f448f9b82476435591d8885d11fe30ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":130},
                "size":{
                  "width":670,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe9b809e8f214f68b4d1bc360c633186",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":392},
            "size":{
              "width":846,
              "height":268}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe692aba57e44bdba2bd93e2c1e7d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":392},
                "size":{
                  "width":846,
                  "height":268}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u23.png"}},
{
          "id":"bf5d5f6a5e0e4ad2a6d96c687414d2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":430,
              "y":340},
            "size":{
              "width":254,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f7107cdb0440ecbda167b6f84203d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":430,
                  "y":340},
                "size":{
                  "width":254,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d77ab403456e49799c7d94fabef4e2a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":379,
              "y":666},
            "size":{
              "width":370,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29e42ce4039a4a45ac0b5b843f400e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":379,
                  "y":666},
                "size":{
                  "width":370,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30b600dd321c4badacfca1f5334bf2cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":110,
              "y":723},
            "size":{
              "width":286,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0159aedd6a074f4db0e97abaf90ef3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":110,
                  "y":723},
                "size":{
                  "width":286,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u29.png"}},
{
          "id":"eeb9e941c4874575914f66a3a94a86a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":439,
              "y":723},
            "size":{
              "width":286,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d476c34659b14812acf44a024aadc95c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":439,
                  "y":723},
                "size":{
                  "width":286,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u29.png"}},
{
          "id":"dfda2a0f9df34abe919e4fb3ecf5eb6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":771,
              "y":723},
            "size":{
              "width":286,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a95af8b5e9b4a9a848dca069faca6a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":771,
                  "y":723},
                "size":{
                  "width":286,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u29.png"}},
{
          "id":"25ee0f49fe704ab0ba0d92e339b954c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":732},
            "size":{
              "width":130,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dd551c5835943cf968c5633e74e39aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":732},
                "size":{
                  "width":130,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u35.png"}},
{
          "id":"3eef392960ce488bad19ff96b351ce26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":731},
            "size":{
              "width":129,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a3c8722f324764b296ee7a53160253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":731},
                "size":{
                  "width":129,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u37.png"}},
{
          "id":"d4176205a6fa4c84a3b614d94f04ff37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":732},
            "size":{
              "width":160,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c641348693e4e32ad440df1f0c5580c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":732},
                "size":{
                  "width":160,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u39.png"}},
{
          "id":"322b3edb5a17416a8869aad89ccb7f77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":790},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5564d116b4b4c8db20310afe9df67f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":790},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u41.png"}},
{
          "id":"b4ae1964d89f4f2fafcee7a2141e30c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":842},
            "size":{
              "width":250,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b09b654dff4d188d5196ec6641828b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":842},
                "size":{
                  "width":250,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34b8bdddcb7b435bbb51a6be6a0cd4ad",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open savefrom.wang/youtube-to-mp3/ in Current Window",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"savefrom.wang/youtube-to-mp3/",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"132c2de6f69640e0a309b2e15f8d2c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":480,
              "y":849},
            "size":{
              "width":204,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d046d95007a64aa68ae164d2475db66d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":849},
                "size":{
                  "width":204,
                  "height":16}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a395bbabc78f458b8155ad2b09e86854",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open savefrom.wang/youtube-to-mp3/ in Current Window",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"savefrom.wang/youtube-to-mp3/",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85e6b963095f45b995ab2e4d4c016b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":805,
              "y":850},
            "size":{
              "width":240,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34b21f19ada4b1496b6f8617f193fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":805,
                  "y":850},
                "size":{
                  "width":240,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c8171b0e8ac4e2bb02aa399fb00f228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":308,
              "y":940},
            "size":{
              "width":511,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"086cdfcb37c3462da40ebe1a2b5cbe32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":308,
                  "y":940},
                "size":{
                  "width":511,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f97f639852fb40eb806e8c6495cadf69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":996},
            "size":{
              "width":770,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b41afd1f1382477b89d795012a764017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":996},
                "size":{
                  "width":770,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78b4ce62ecb2491f9921ec766cabd47a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":429,
              "y":1100},
            "size":{
              "width":232,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da3478b933e49a2a198f49d7999c3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":429,
                  "y":1100},
                "size":{
                  "width":232,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a246b85028d04036a4193381da34082e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":110,
              "y":1156},
            "size":{
              "width":947,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f6cd0564e345539f6a679a96c28b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":110,
                  "y":1156},
                "size":{
                  "width":947,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbf87ee487774da89deeac9b8e84e919",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":1279},
            "size":{
              "width":982,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c767190f836443fa2fedb5fe5ab121a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":1279},
                "size":{
                  "width":982,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u59.png"}},
{
          "id":"fd9f2cf845c9437d896083d602707922",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":1311},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98eb6d200a2a407b8bc8535fbe5b186a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":1311},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u61.png"}},
{
          "id":"ca503d007d0e4debbe9cb7a403aa4e1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":1350},
            "size":{
              "width":490,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"744ff3d32a874b558ef96c4c2ba3d550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":1350},
                "size":{
                  "width":490,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u63.png"}},
{
          "id":"5a59501150d94952857946312a54ec86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":647,
              "y":1361},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73157289164f4642b56a7fbfa8501a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":647,
                  "y":1361},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"758535694bb940819e22b444d77a5af9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":797,
              "y":1361},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e670b6a891434cbd0b87c286965bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":797,
                  "y":1361},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f095a65e25fe4d8e8f03efd01cf4b16c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":19},
            "size":{
              "width":69,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d1b8c533114456abe5999f55f7f03eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":19},
                "size":{
                  "width":69,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/savefrom/u69.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0797725e50834de78e469ed0a4741176":{
      "scriptId":"u0"},
    "949bf6929764447688e040785fc0c4be":{
      "scriptId":"u1"},
    "d8f2ee293f7d4e109dfbaaac2a4e252b":{
      "scriptId":"u2"},
    "be8930ddacef4e24b0148a05e20e3e18":{
      "scriptId":"u3"},
    "357128ce7fea41178ae537d4a825fae3":{
      "scriptId":"u4"},
    "dd6847c4b910412a9e90749631766e60":{
      "scriptId":"u5"},
    "28028f3cd21b4fa8a08e434295d332a2":{
      "scriptId":"u6"},
    "f20fa0aa0c0047898bbf848e61223359":{
      "scriptId":"u7"},
    "2b9e3108c1d04eeabdd851b8a7762411":{
      "scriptId":"u8"},
    "aac44495b5164648ab7d148e4e9d37a9":{
      "scriptId":"u9"},
    "b9b5513d5f874f80a9f0f584aa1fa1e5":{
      "scriptId":"u10"},
    "e8209f15467842debba6db306960fd41":{
      "scriptId":"u11"},
    "cfb31efd09144f798aaa7cc7bee362cf":{
      "scriptId":"u12"},
    "70f179876f9a4053ba4eee9603366757":{
      "scriptId":"u13"},
    "4173c237d044429b9b24a06d87fa11f0":{
      "scriptId":"u14"},
    "169557af81414c0c871c0bdef9295d74":{
      "scriptId":"u15"},
    "4c364484a98e4ca9ba0f014eb6dcd696":{
      "scriptId":"u16"},
    "3f0afaeac40940f58235aeb58cc71cb5":{
      "scriptId":"u17"},
    "8f5180b1a27b48c7ae039d84f73b7413":{
      "scriptId":"u18"},
    "42010712318b461ea2c5bce02dd2bfed":{
      "scriptId":"u19"},
    "78f84b997acf4d47bb764e84326cd210":{
      "scriptId":"u20"},
    "fa53287881534bdf8d6cdf5fb4457bb8":{
      "scriptId":"u21"},
    "f448f9b82476435591d8885d11fe30ea":{
      "scriptId":"u22"},
    "fe9b809e8f214f68b4d1bc360c633186":{
      "scriptId":"u23"},
    "6fe692aba57e44bdba2bd93e2c1e7d93":{
      "scriptId":"u24"},
    "bf5d5f6a5e0e4ad2a6d96c687414d2de":{
      "scriptId":"u25"},
    "13f7107cdb0440ecbda167b6f84203d7":{
      "scriptId":"u26"},
    "d77ab403456e49799c7d94fabef4e2a0":{
      "scriptId":"u27"},
    "29e42ce4039a4a45ac0b5b843f400e5c":{
      "scriptId":"u28"},
    "30b600dd321c4badacfca1f5334bf2cd":{
      "scriptId":"u29"},
    "0159aedd6a074f4db0e97abaf90ef3e5":{
      "scriptId":"u30"},
    "eeb9e941c4874575914f66a3a94a86a0":{
      "scriptId":"u31"},
    "d476c34659b14812acf44a024aadc95c":{
      "scriptId":"u32"},
    "dfda2a0f9df34abe919e4fb3ecf5eb6b":{
      "scriptId":"u33"},
    "3a95af8b5e9b4a9a848dca069faca6a1":{
      "scriptId":"u34"},
    "25ee0f49fe704ab0ba0d92e339b954c4":{
      "scriptId":"u35"},
    "7dd551c5835943cf968c5633e74e39aa":{
      "scriptId":"u36"},
    "3eef392960ce488bad19ff96b351ce26":{
      "scriptId":"u37"},
    "02a3c8722f324764b296ee7a53160253":{
      "scriptId":"u38"},
    "d4176205a6fa4c84a3b614d94f04ff37":{
      "scriptId":"u39"},
    "6c641348693e4e32ad440df1f0c5580c":{
      "scriptId":"u40"},
    "322b3edb5a17416a8869aad89ccb7f77":{
      "scriptId":"u41"},
    "d5564d116b4b4c8db20310afe9df67f5":{
      "scriptId":"u42"},
    "b4ae1964d89f4f2fafcee7a2141e30c3":{
      "scriptId":"u43"},
    "86b09b654dff4d188d5196ec6641828b":{
      "scriptId":"u44"},
    "34b8bdddcb7b435bbb51a6be6a0cd4ad":{
      "scriptId":"u45"},
    "132c2de6f69640e0a309b2e15f8d2c3e":{
      "scriptId":"u46"},
    "d046d95007a64aa68ae164d2475db66d":{
      "scriptId":"u47"},
    "a395bbabc78f458b8155ad2b09e86854":{
      "scriptId":"u48"},
    "85e6b963095f45b995ab2e4d4c016b1a":{
      "scriptId":"u49"},
    "a34b21f19ada4b1496b6f8617f193fde":{
      "scriptId":"u50"},
    "7c8171b0e8ac4e2bb02aa399fb00f228":{
      "scriptId":"u51"},
    "086cdfcb37c3462da40ebe1a2b5cbe32":{
      "scriptId":"u52"},
    "f97f639852fb40eb806e8c6495cadf69":{
      "scriptId":"u53"},
    "b41afd1f1382477b89d795012a764017":{
      "scriptId":"u54"},
    "78b4ce62ecb2491f9921ec766cabd47a":{
      "scriptId":"u55"},
    "9da3478b933e49a2a198f49d7999c3af":{
      "scriptId":"u56"},
    "a246b85028d04036a4193381da34082e":{
      "scriptId":"u57"},
    "21f6cd0564e345539f6a679a96c28b78":{
      "scriptId":"u58"},
    "dbf87ee487774da89deeac9b8e84e919":{
      "scriptId":"u59"},
    "5c767190f836443fa2fedb5fe5ab121a":{
      "scriptId":"u60"},
    "fd9f2cf845c9437d896083d602707922":{
      "scriptId":"u61"},
    "98eb6d200a2a407b8bc8535fbe5b186a":{
      "scriptId":"u62"},
    "ca503d007d0e4debbe9cb7a403aa4e1d":{
      "scriptId":"u63"},
    "744ff3d32a874b558ef96c4c2ba3d550":{
      "scriptId":"u64"},
    "5a59501150d94952857946312a54ec86":{
      "scriptId":"u65"},
    "73157289164f4642b56a7fbfa8501a20":{
      "scriptId":"u66"},
    "758535694bb940819e22b444d77a5af9":{
      "scriptId":"u67"},
    "45e670b6a891434cbd0b87c286965bb1":{
      "scriptId":"u68"},
    "f095a65e25fe4d8e8f03efd01cf4b16c":{
      "scriptId":"u69"},
    "6d1b8c533114456abe5999f55f7f03eb":{
      "scriptId":"u70"}}});